# Generated by Django 4.0.4 on 2022-04-20 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_image_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='proba',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelfile',
            name='registered_date',
            field=models.DateField(default=datetime.date(2022, 4, 20)),
        ),
        migrations.AddField(
            model_name='modelfile',
            name='result',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
