# Generated by Django 4.0.4 on 2022-04-20 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_image_app', '0002_modelfile_proba_modelfile_registered_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegeInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('knowledge', models.CharField(max_length=255)),
                ('registered_date', models.DateField(default=datetime.date(2022, 4, 21))),
            ],
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='registered_date',
            field=models.DateField(default=datetime.date(2022, 4, 21)),
        ),
    ]
